#!/bin/sh

# Syncs repositories and downloads updates, meant to be run as a cronjob.
fyi -a update -r 69 "📦 Repository Sync" "Checking for package updates..."

sudo pacman -Syyuw --noconfirm || fyi -a update "Error downloading updates. Check your internet connection, if pacman is already running, or run update manually to see errors."

if pacman -Qu | grep -v "\[ignored\]"
then
  act=$(fyi -r 69 -a update -t 0 -A default:fuck "🎁 Repository Sync" "Updates available.")
else
  fyi -a update -r 69 "📦 Repository Sync" "Sync complete. No new packages for update."
fi

[ "$act" = "action=default" ] && footclient -a popp -e popupgrade
