#!/bin/bash

# This scrip reads your clipboard and tries to play the http links in mpv.

# Read link from clipboard.
link1=$(xclip -sel c -out | grep -Ex '.*\:\/\/.*\..*')
link2=$(cat ~/.cache/clipmenu/clipmenu.6.noob/line_cache | cut -d ' ' -f2 | grep -Ex '.*\:\/\/.*\..*' | head -n1)

# Try to stream from the links.
if [ -n $link1 ]; then
	notify-send 'Trying to play Media in mpv' ; mpv "$link1" && exit 0
elif
	[ -n $link2 ]; then
	notify-send 'Trying to play Media in mpv' ; mpv "$link2" && exit 0
else
	notify-send "Oops" "No, URL found in ClipBoard"
fi
