#!/bin/env bash

if [ -d $HOME/.cache/piratebay ]; then
	cachedir=$HOME/.cache/piratebay
else
	mkdir $HOME/.cache/piratebay && cachedir=$HOME/.cache/piratebay
fi

# Take input.
if [ -z $1 ]; then
	query=$(dmenu -p "Search Torrent: " <&-)
else
	query=$*
fi

query="$(echo $query | sed 's/ /+/g')"

# Get the required output form webpage.
curl "https://arrrr.ga/api.php?url=/q.php?q=$query&cat=" | jq '.[] | {name, info_hash}' | sed -E 's/[{}]/\n/g' > $cachedir/names.txt

# Dmenu list for names of torrents.
name=$(grep -E '\"name\": \".*\",' $cachedir/names.txt | cut -d\" -f4 | dmenu -l 10)
ih=$(grep -EA1 "$name" $cachedir/names.txt | head -n2 | grep -E '\"info_hash\": \".*\"' | cut -d\" -f4)

name=$(echo $name | sed 's/ /%20/g' | sed 's/:/%3A/g')

# Generate the magnet link.
magnet="magnet:?xt=urn:btih:$ih&dn=$name&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2920%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce"

# Choice to Stream or Download
choice=$(printf "Stream\nDownload\nCopyout" | dmenu -i )
[ $choice = Stream ] && webtorrent "$magnet" --mpv
[ $choice = Download ] && transadd "$magnet" && exit 0
[ $choice = Copyout ] && echo "$magnet" | xclip -sel c && notify-send "Link copied to Clipboard" && exit 0
[ -z $choice ] && notify-send "No Results selected. Exiting... 🔴" && exit 0
