#!/usr/bin/env zsh
source /home/siki/.config/zsh/functions.zsh

if [[ -f "/tmp/recordilock" ]]; then
  kill -s INT $(pidof wf-recorder)
else;
  touch /tmp/recordilock
  wf-recorder -Dyf ~/vid/sr/original.mp4
  ffmpeg -y -i ~/vid/sr/original.mp4 \
    -an \
    -c:v libx264 -preset medium -crf 21 \
    -movflags +faststart \
    -b:v 3M -maxrate 4.5M -bufsize 6M \
    ~/vid/sr/compressed.mp4
  rm -f /tmp/recordilock
  copyl ~/vid/sr/compressed.mp4
fi
