#!/bin/sh
# A dmenu wrapper script for system functions.
case "$(readlink -f /sbin/init)" in
	*systemd*) ctl='systemctl' ;;
	*) ctl='loginctl' ;;
esac

case "$(printf " lock\n log out\n renew dwm\n🐻 hibernate\n💤 sleep\n reboot\n shutdown" | dmenu -i -b)" in
	' lock') gpg-connect-agent --no-autostart reloadagent /bye && xset dpms force off; slock ;;
	' log out') kill -TERM "$(pgrep -u "$USER" "\bdwm$")" ;;
	' renew dwm') kill -HUP "$(pgrep -u "$USER" "\bdwm$")" ;;
	'🐻 hibernate') slock $ctl hibernate ;;
	'💤 sleep') slock & $ctl suspend ;;
	' reboot') $ctl reboot ;;
	' shutdown') $ctl poweroff ;;
	*) exit 1 ;;
esac
